#!/bin/python

# This script will get rid of any duplicates generated by:
# ps -axch -o cmd,%mem --sort=-%mem

import sys

programs = {}
for line in sys.stdin:
    a, b = line.split()
    if a in programs:
        programs[a] += float(b)
    else:
        programs[a] = float(b)

for key in programs:
    print( key, round(programs[key], 1) )

